import type { Metadata } from 'next';
import { Arsenal } from 'next/font/google';
import { Suspense } from 'react';

import { ApiDemoCounter, footballApiService } from '@shared/api/football-api';
import { Icon } from '@shared/ui/icon';
import { cn } from '@shared/utils';
import { BottomNavigation } from '@widgets/bottom-navigation';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const arsenalFont = Arsenal({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accountStatus = footballApiService.getAccountStatus();
  return (
    <html lang="en">
      <body className={cn(arsenalFont.className, 'relative min-h-svh pb-10')}>
        {children}
        <div className="absolute bottom-2 right-2 flex h-10 items-center justify-center">
          <Suspense
            fallback={<Icon type="common" name="loader" size="small" />}
          >
            <ApiDemoCounter accountStatusData={accountStatus} />
          </Suspense>
        </div>
        <div className="fixed bottom-1 left-1/2 w-4/5 -translate-x-1/2 rounded-md bg-background/80">
          <div className="">
            <BottomNavigation />
          </div>
        </div>
      </body>
    </html>
  );
}
