import type { Metadata } from 'next';
import { Arsenal } from 'next/font/google';
import { Suspense } from 'react';

import { ApiDemoCounter, footballApiService } from '@shared/api/football-api';
import { Icon } from '@shared/ui/icon';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const arsenalFont = Arsenal({
  subsets: ['latin'],
  weight: ['400',  '700'],
  display: 'swap',
});

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accountStatus = footballApiService.getAccountStatus();
  return (
    <html lang="en">
      <body className={arsenalFont.className}>
        {children}
        <div className="absolute bottom-2 right-2 flex h-10 items-center justify-center">
          <Suspense
            fallback={<Icon type="common" name="loader" size="small" />}
          >
            <ApiDemoCounter accountStatusData={accountStatus} />
          </Suspense>
        </div>
      </body>
    </html>
  );
}
