import type { Metadata } from 'next';
import { Titillium_Web } from 'next/font/google';

import { ApiDemoCounter } from '@shared/api/football-api';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const titillium = Titillium_Web({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={titillium.className}>
        {children}
        <div className="absolute bottom-2 right-2 flex h-10 items-center justify-center">
          <ApiDemoCounter />
        </div>
      </body>
    </html>
  );
}
